---
title: "Simulating sampling schemes"
author: "Richard Meitern"
date: "7/9/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This file is for demonstrating the new simulation function that incorporates Coeficent intervals. The work is based on Nuno's script and refractored from it. It is still work in progess, ie some things might not work well (or not at all). Also the functions are lackng documentation (but it is comming at some point).

```{r}
privateDataFile <- "../privateData/rcgEE2019.Rdata"
#load(privateDataFile)
```



## Simulations

```{r}
setwd("/home/rix133/Documents/software/ICES/RCG_BA/SmallPelag/SimsGroup2")

#load functions
source("./R/validators.R")
source("./R/simulators.R")

# read packages [not sure all are used but...]
library(data.table)


#read data
filename<-"./testData.Rdata"
load(filename)

# load vector of vessels in frame
filename<-"./target_list.Rdata"
load(filename)
```


```{r}
#----------------Options----------------------	

# withinTripSampUnit
# this is what will be sampled withinTrip
withinTripSampUnit <- "haulId" # alternative: "fishdayId"
			
# withinTripSampMethod	
withinTripSampMethod <- "all_hauls" # alternative: "first_haul", "last_haul", "srswor_haul"
		
# sppSelectMethod
sppSelectMethod <- "alternative_3" # alternative: "alternative_1", "alternative_2", "alternative_3", and so on
target_spp<-c("Sprattus sprattus", "Clupea harengus") # if not NULL keep only selected species
sign_prop <- 0.3 # only for alternative 3
		
# subsampleHaulsPerSubdivision	
subsampleHaulsPerArea<- TRUE # alternative: TRUE, FALSE
nHaulsMaxPerArea<-2
			
# creates withinTripSampUnit column
keep_areas <-  c("27.3.d.24","27.3.d.25","27.3.d.26","27.3.d.27","27.3.d.28.2","27.3.d.29")
```


```{r}
#-----------Validate data format ----------
testData<- checkInputDataValidity(testData, withinTripSampUnit = "haulId" )
```


```{r}
# ======================
# example of simulation
# ======================
res <- simulateSampling(data = testData,
                        refusals = 20,
                        sppSelectMethod = sppSelectMethod,
                        target_vessels = target_list,
                        target_spp = target_spp,
                        keep_areas = keep_areas,
                        withinTripSampMethod = withinTripSampMethod,
                        withinTripSampUnit = withinTripSampUnit,
                        n_vessels = 5,
                        n_sims = 10)
```





































